name: Build and Deploy
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: show php version
        run:  php --version
      - name: Process index.php
        run: php -f docs/index.php
      - name: Never use a secret value in echo command!
        run: echo ${{ secrets.MY_FIRST_SECRET }}
